<a href="https://colab.research.google.com/github/JoonYoung-Sohn/practice/blob/master/201202_RNN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from keras.models import Sequential
from keras.layers import SimpleRNN

In [2]:
model = Sequential()
model.add(SimpleRNN(3, input_shape=(2,10)))
# model.add(SimpleRNN(3, input_length=2, input_dim=10))
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
simple_rnn (SimpleRNN)       (None, 3)                 42        
Total params: 42
Trainable params: 42
Non-trainable params: 0
_________________________________________________________________


In [3]:
model = Sequential()
model.add(SimpleRNN(3, batch_input_shape=(8,2,10)))
model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
simple_rnn_1 (SimpleRNN)     (8, 3)                    42        
Total params: 42
Trainable params: 42
Non-trainable params: 0
_________________________________________________________________


In [4]:
model = Sequential()
model.add(SimpleRNN(3, batch_input_shape=(8,2,10), return_sequences=True))
model.summary()

Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
simple_rnn_2 (SimpleRNN)     (8, 2, 3)                 42        
Total params: 42
Trainable params: 42
Non-trainable params: 0
_________________________________________________________________


In [5]:
import numpy as np

timesteps = 10 # 시점의 수. NLP에서는 보통 문장의 길이가 된다.
input_dim = 4 # 입력의 차원. NLP에서는 보통 단어 벡터의 차원이 된다.
hidden_size = 8 # 은닉 상태의 크기. 메모리 셀의 용량이다.

inputs = np.random.random((timesteps, input_dim)) # 입력에 해당되는 2D 텐서

hidden_state_t = np.zeros((hidden_size,)) # 초기 은닉 상태는 0(벡터)로 초기화

In [6]:
print(hidden_state_t)

[0. 0. 0. 0. 0. 0. 0. 0.]


In [8]:
Wx = np.random.random((hidden_size, input_dim))  # (8, 4)크기의 2D 텐서 생성. 입력에 대한 가중치.
Wh = np.random.random((hidden_size, hidden_size)) # (8, 8)크기의 2D 텐서 생성. 은닉 상태에 대한 가중치.
b = np.random.random((hidden_size,)) # (8,)크기의 1D 텐서 생성. 이 값은 편향(bias).

In [9]:
print(np.shape(Wx))
print(np.shape(Wh))
print(np.shape(b))

(8, 4)
(8, 8)
(8,)


In [10]:
total_hidden_states = []

for input_t in inputs: 
  output_t = np.tanh(np.dot(Wx,input_t) + np.dot(Wh,hidden_state_t) + b) # Wx * Xt + Wh * Ht-1 + b(bias)
  total_hidden_states.append(list(output_t)) 
  print(np.shape(total_hidden_states)) #(timestep, output_dim)
  hidden_state_t = output_t

total_hidden_states = np.stack(total_hidden_states, axis = 0) 

print(total_hidden_states) # (timesteps, output_dim)의 크기. 

(1, 8)
(2, 8)
(3, 8)
(4, 8)
(5, 8)
(6, 8)
(7, 8)
(8, 8)
(9, 8)
(10, 8)
[[0.94650423 0.9709604  0.93717172 0.8278919  0.81600463 0.54879451
  0.96677856 0.89983669]
 [0.99956463 0.99989191 0.99999306 0.99944268 0.99994495 0.99938579
  0.99996848 0.99992677]
 [0.99976714 0.99988638 0.99999719 0.99974643 0.99997814 0.9997548
  0.99997243 0.99995337]
 [0.99995289 0.99998262 0.99999885 0.99990957 0.99999542 0.99984943
  0.99999597 0.99999565]
 [0.99996867 0.99999259 0.99999966 0.99997438 0.99999851 0.99989408
  0.99999924 0.99999886]
 [0.99994347 0.99998412 0.9999988  0.99985268 0.99999362 0.99984836
  0.99999651 0.99999633]
 [0.99974029 0.99991904 0.99999872 0.99985829 0.99998844 0.99977527
  0.99999286 0.99998564]
 [0.99996598 0.99998627 0.99999918 0.9999536  0.99999548 0.99989449
  0.99999377 0.99998833]
 [0.99996628 0.99998964 0.99999927 0.99994288 0.99999695 0.99987856
  0.99999778 0.99999731]
 [0.99993413 0.99997277 0.99999823 0.99984681 0.99999071 0.9998373
  0.99999002 0.99998784]]


In [11]:
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
import numpy as np
from tensorflow.keras.utils import to_categorical

In [12]:
text="""경마장에 있는 말이 뛰고 있다\n
그의 말이 법이다\n
가는 말이 고와야 오는 말이 곱다\n"""

In [13]:
t = Tokenizer()
t.fit_on_texts([text])
vocab_size = len(t.word_index) + 1
print('단어 집합의 크기 : %d' % vocab_size)

단어 집합의 크기 : 12


In [14]:
print(t.word_index)

{'말이': 1, '경마장에': 2, '있는': 3, '뛰고': 4, '있다': 5, '그의': 6, '법이다': 7, '가는': 8, '고와야': 9, '오는': 10, '곱다': 11}


In [15]:
sequences = list()
for line in text.split('\n'): 
    encoded = t.texts_to_sequences([line])[0]
    for i in range(1, len(encoded)):
        sequence = encoded[:i+1]
        sequences.append(sequence)

print('학습에 사용할 샘플의 개수: %d' % len(sequences))

학습에 사용할 샘플의 개수: 11


In [16]:
print(sequences)

[[2, 3], [2, 3, 1], [2, 3, 1, 4], [2, 3, 1, 4, 5], [6, 1], [6, 1, 7], [8, 1], [8, 1, 9], [8, 1, 9, 10], [8, 1, 9, 10, 1], [8, 1, 9, 10, 1, 11]]


In [17]:
max_len=max(len(l) for l in sequences)
print('샘플의 최대 길이 : {}'.format(max_len))

샘플의 최대 길이 : 6


In [19]:
sequences = pad_sequences(sequences, maxlen=max_len, padding='pre')
print(sequences)

[[ 0  0  0  0  2  3]
 [ 0  0  0  2  3  1]
 [ 0  0  2  3  1  4]
 [ 0  2  3  1  4  5]
 [ 0  0  0  0  6  1]
 [ 0  0  0  6  1  7]
 [ 0  0  0  0  8  1]
 [ 0  0  0  8  1  9]
 [ 0  0  8  1  9 10]
 [ 0  8  1  9 10  1]
 [ 8  1  9 10  1 11]]


In [20]:
sequences = np.array(sequences)
X = sequences[:,:-1]
y = sequences[:,-1]

In [21]:
print(X)
print(y)

[[ 0  0  0  0  2]
 [ 0  0  0  2  3]
 [ 0  0  2  3  1]
 [ 0  2  3  1  4]
 [ 0  0  0  0  6]
 [ 0  0  0  6  1]
 [ 0  0  0  0  8]
 [ 0  0  0  8  1]
 [ 0  0  8  1  9]
 [ 0  8  1  9 10]
 [ 8  1  9 10  1]]
[ 3  1  4  5  1  7  1  9 10  1 11]


In [22]:
y = to_categorical(y, num_classes=vocab_size)

In [23]:
print(y)

[[0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


In [24]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, Dense, SimpleRNN

In [25]:
model = Sequential()
model.add(Embedding(vocab_size, 10, input_length=max_len-1)) 
model.add(SimpleRNN(32))
model.add(Dense(vocab_size, activation='softmax'))
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
model.fit(X, y, epochs=200, verbose=2)

Epoch 1/200
1/1 - 0s - loss: 2.4892 - accuracy: 0.0000e+00
Epoch 2/200
1/1 - 0s - loss: 2.4734 - accuracy: 0.0000e+00
Epoch 3/200
1/1 - 0s - loss: 2.4579 - accuracy: 0.2727
Epoch 4/200
1/1 - 0s - loss: 2.4425 - accuracy: 0.4545
Epoch 5/200
1/1 - 0s - loss: 2.4270 - accuracy: 0.4545
Epoch 6/200
1/1 - 0s - loss: 2.4115 - accuracy: 0.4545
Epoch 7/200
1/1 - 0s - loss: 2.3956 - accuracy: 0.4545
Epoch 8/200
1/1 - 0s - loss: 2.3794 - accuracy: 0.3636
Epoch 9/200
1/1 - 0s - loss: 2.3626 - accuracy: 0.3636
Epoch 10/200
1/1 - 0s - loss: 2.3452 - accuracy: 0.3636
Epoch 11/200
1/1 - 0s - loss: 2.3271 - accuracy: 0.3636
Epoch 12/200
1/1 - 0s - loss: 2.3082 - accuracy: 0.3636
Epoch 13/200
1/1 - 0s - loss: 2.2884 - accuracy: 0.3636
Epoch 14/200
1/1 - 0s - loss: 2.2676 - accuracy: 0.3636
Epoch 15/200
1/1 - 0s - loss: 2.2460 - accuracy: 0.3636
Epoch 16/200
1/1 - 0s - loss: 2.2234 - accuracy: 0.3636
Epoch 17/200
1/1 - 0s - loss: 2.1999 - accuracy: 0.3636
Epoch 18/200
1/1 - 0s - loss: 2.1756 - accuracy: 

In [26]:
def sentence_generation(model, t, current_word, n): # 모델, 토크나이저, 현재 단어, 반복할 횟수
    init_word = current_word # 처음 들어온 단어도 마지막에 같이 출력하기위해 저장
    sentence = ''
    for _ in range(n): # n번 반복
        encoded = t.texts_to_sequences([current_word])[0] # 현재 단어에 대한 정수 인코딩
        encoded = pad_sequences([encoded], maxlen=5, padding='pre') # 데이터에 대한 패딩
        result = model.predict_classes(encoded, verbose=0)
    # 입력한 X(현재 단어)에 대해서 Y를 예측하고 Y(예측한 단어)를 result에 저장.
        for word, index in t.word_index.items(): 
            if index == result: # 만약 예측한 단어와 인덱스와 동일한 단어가 있다면
                break # 해당 단어가 예측 단어이므로 break
        current_word = current_word + ' '  + word # 현재 단어 + ' ' + 예측 단어를 현재 단어로 변경
        sentence = sentence + ' ' + word # 예측 단어를 문장에 저장
    # for문이므로 이 행동을 다시 반복
    sentence = init_word + sentence
    return sentence

In [27]:
print(sentence_generation(model, t, '경마장에', 4))

Instructions for updating:
Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).
경마장에 있는 말이 뛰고 있다


In [28]:
print(sentence_generation(model, t, '그의', 2))

그의 말이 법이다


In [29]:
print(sentence_generation(model, t, '가는', 5))

가는 말이 고와야 오는 말이 곱다


In [30]:
import pandas as pd
from string import punctuation
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
import numpy as np
from tensorflow.keras.utils import to_categorical

In [31]:
from google.colab import files
file = files.upload()

Saving ArticlesApril2018.csv to ArticlesApril2018.csv


In [32]:
df=pd.read_csv('ArticlesApril2018.csv')

In [33]:
df.head()

articleID  ...                                             webURL
0  5adf6684068401528a2aa69b  ...  https://www.nytimes.com/2018/04/24/sports/foot...
1  5adf653f068401528a2aa697  ...  https://www.nytimes.com/2018/04/24/climate/epa...
2  5adf4626068401528a2aa628  ...  https://www.nytimes.com/2018/04/24/dining/noma...
3  5adf40d2068401528a2aa619  ...  https://www.nytimes.com/2018/04/24/world/europ...
4  5adf3d64068401528a2aa60f  ...  https://www.nytimes.com/2018/04/24/world/canad...

[5 rows x 15 columns]

In [34]:
print('열의 개수: ',len(df.columns))
print(df.columns)

열의 개수:  15
Index(['articleID', 'articleWordCount', 'byline', 'documentType', 'headline',
       'keywords', 'multimedia', 'newDesk', 'printPage', 'pubDate',
       'sectionName', 'snippet', 'source', 'typeOfMaterial', 'webURL'],
      dtype='object')


In [35]:
df['headline'].isnull().values.any()

False

In [36]:
headline = [] 
headline.extend(list(df.headline.values))
headline[:5] 

['Former N.F.L. Cheerleaders’ Settlement Offer: $1 and a Meeting With Goodell',
 'E.P.A. to Unveil a New Rule. Its Effect: Less Science in Policymaking.',
 'The New Noma, Explained',
 'Unknown',
 'Unknown']

In [37]:
print('총 샘플의 개수 : {}'.format(len(headline)))

총 샘플의 개수 : 1324


In [38]:
headline = [n for n in headline if n != "Unknown"] 
print('노이즈값 제거 후 샘플의 개수 : {}'.format(len(headline)))

노이즈값 제거 후 샘플의 개수 : 1214


In [39]:
headline[:5]

['Former N.F.L. Cheerleaders’ Settlement Offer: $1 and a Meeting With Goodell',
 'E.P.A. to Unveil a New Rule. Its Effect: Less Science in Policymaking.',
 'The New Noma, Explained',
 'How a Bag of Texas Dirt  Became a Times Tradition',
 'Is School a Place for Self-Expression?']

In [40]:
def repreprocessing(s):
    s=s.encode("utf8").decode("ascii",'ignore')
    return ''.join(c for c in s if c not in punctuation).lower() # 구두점 제거와 동시에 소문자화

text = [repreprocessing(x) for x in headline]
text[:5]

['former nfl cheerleaders settlement offer 1 and a meeting with goodell',
 'epa to unveil a new rule its effect less science in policymaking',
 'the new noma explained',
 'how a bag of texas dirt  became a times tradition',
 'is school a place for selfexpression']

In [41]:
t = Tokenizer()
t.fit_on_texts(text)
vocab_size = len(t.word_index) + 1
print('단어 집합의 크기 : %d' % vocab_size)

단어 집합의 크기 : 3494


In [42]:
sequences = list()

for line in text: 
    encoded = t.texts_to_sequences([line])[0] 
    for i in range(1, len(encoded)):
        sequence = encoded[:i+1]
        sequences.append(sequence)

sequences[:11]

[[99, 269],
 [99, 269, 371],
 [99, 269, 371, 1115],
 [99, 269, 371, 1115, 582],
 [99, 269, 371, 1115, 582, 52],
 [99, 269, 371, 1115, 582, 52, 7],
 [99, 269, 371, 1115, 582, 52, 7, 2],
 [99, 269, 371, 1115, 582, 52, 7, 2, 372],
 [99, 269, 371, 1115, 582, 52, 7, 2, 372, 10],
 [99, 269, 371, 1115, 582, 52, 7, 2, 372, 10, 1116],
 [100, 3]]

In [44]:
index_to_word={}
for key, value in t.word_index.items(): 
    index_to_word[value] = key

print('빈도수 상위 100번 단어 : {}'.format(index_to_word[100]))

빈도수 상위 100번 단어 : epa


In [45]:
max_len=max(len(l) for l in sequences)
print('샘플의 최대 길이 : {}'.format(max_len))

샘플의 최대 길이 : 24


In [46]:
sequences = pad_sequences(sequences, maxlen=max_len, padding='pre')
print(sequences[:3])

[[   0    0    0    0    0    0    0    0    0    0    0    0    0    0
     0    0    0    0    0    0    0    0   99  269]
 [   0    0    0    0    0    0    0    0    0    0    0    0    0    0
     0    0    0    0    0    0    0   99  269  371]
 [   0    0    0    0    0    0    0    0    0    0    0    0    0    0
     0    0    0    0    0    0   99  269  371 1115]]


In [47]:
sequences = np.array(sequences)
X = sequences[:,:-1]
y = sequences[:,-1]

In [48]:
y = to_categorical(y, num_classes=vocab_size)

In [49]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, Dense, LSTM

In [50]:
model = Sequential()
model.add(Embedding(vocab_size, 10, input_length=max_len-1))
model.add(LSTM(128))
model.add(Dense(vocab_size, activation='softmax'))
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
model.fit(X, y, epochs=200, verbose=2)

Epoch 1/200
244/244 - 7s - loss: 7.6335 - accuracy: 0.0259
Epoch 2/200
244/244 - 7s - loss: 7.1076 - accuracy: 0.0288
Epoch 3/200
244/244 - 7s - loss: 6.9680 - accuracy: 0.0314
Epoch 4/200
244/244 - 7s - loss: 6.8389 - accuracy: 0.0408
Epoch 5/200
244/244 - 7s - loss: 6.6876 - accuracy: 0.0436
Epoch 6/200
244/244 - 7s - loss: 6.5193 - accuracy: 0.0481
Epoch 7/200
244/244 - 7s - loss: 6.3244 - accuracy: 0.0538
Epoch 8/200
244/244 - 7s - loss: 6.1221 - accuracy: 0.0590
Epoch 9/200
244/244 - 7s - loss: 5.9242 - accuracy: 0.0642
Epoch 10/200
244/244 - 7s - loss: 5.7313 - accuracy: 0.0681
Epoch 11/200
244/244 - 7s - loss: 5.5495 - accuracy: 0.0734
Epoch 12/200
244/244 - 7s - loss: 5.3800 - accuracy: 0.0759
Epoch 13/200
244/244 - 7s - loss: 5.2189 - accuracy: 0.0847
Epoch 14/200
244/244 - 7s - loss: 5.0664 - accuracy: 0.0897
Epoch 15/200
244/244 - 7s - loss: 4.9198 - accuracy: 0.1001
Epoch 16/200
244/244 - 7s - loss: 4.7811 - accuracy: 0.1098
Epoch 17/200
244/244 - 7s - loss: 4.6471 - accura

In [51]:
def sentence_generation(model, t, current_word, n): # 모델, 토크나이저, 현재 단어, 반복할 횟수
    init_word = current_word # 처음 들어온 단어도 마지막에 같이 출력하기위해 저장
    sentence = ''
    for _ in range(n): # n번 반복
        encoded = t.texts_to_sequences([current_word])[0] # 현재 단어에 대한 정수 인코딩
        encoded = pad_sequences([encoded], maxlen=23, padding='pre') # 데이터에 대한 패딩
        result = model.predict_classes(encoded, verbose=0)
    # 입력한 X(현재 단어)에 대해서 y를 예측하고 y(예측한 단어)를 result에 저장.
        for word, index in t.word_index.items(): 
            if index == result: # 만약 예측한 단어와 인덱스와 동일한 단어가 있다면
                break # 해당 단어가 예측 단어이므로 break
        current_word = current_word + ' '  + word # 현재 단어 + ' ' + 예측 단어를 현재 단어로 변경
        sentence = sentence + ' ' + word # 예측 단어를 문장에 저장
    # for문이므로 이 행동을 다시 반복
    sentence = init_word + sentence
    return sentence

In [52]:
print(sentence_generation(model, t, 'i', 10))

i want to be rich and im not sorry think hes


In [53]:
print(sentence_generation(model, t, 'how', 10))

how to win an argument about guns hair gop can case
